version: "3.8"

networks:
  web-server-network:
    name: web-server-network
    external: true

services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "$UID:$GID"
    networks:
      - default
      - web-server-network
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
